# Generated by Django 5.2 on 2025-05-06 20:14

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, max_length=24, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('profile_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
