# Generated by Django 5.2 on 2025-05-08 17:10

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0002_companyprofile_business_risk_insight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, max_length=24, primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=255)),
                ('trend_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact_level', models.IntegerField(default=3)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='annual_revenue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='crunchbase_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='employee_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='funding_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='stock_symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, max_length=24, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_user_message', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='researcher.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorRelation',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, max_length=24, primary_key=True, serialize=False)),
                ('competitor_name', models.CharField(max_length=255)),
                ('competitor_website', models.URLField(blank=True, null=True)),
                ('relationship_strength', models.IntegerField(default=1)),
                ('competitive_areas', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='researcher.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveTeam',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='researcher.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, max_length=24, primary_key=True, serialize=False)),
                ('round_type', models.CharField(max_length=50)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('lead_investors', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='researcher.companyprofile')),
            ],
        ),
    ]
